hunter_config(OpenSSL VERSION 1.0.2k)
hunter_config(PocoCpp VERSION 1.7.6-p0 CMAKE_ARGS ENABLE_MONGODB=ON ENABLE_NETSSL=ON ENABLE_CRYPTO=ON ENABLE_DATA=ON ENABLE_PAGECOMPILER=ON ENABLE_PAGECOMPILER_FILE2PAGE=ON)
